# Generated by Django 5.2.7 on 2025-12-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='Stanowisko',
            new_name='stanowisko',
        ),
    ]
