# Generated by Django 5.2.7 on 2025-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default='2025-11-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta'), (3, 'Inna')], default=3),
        ),
    ]
